Mailing list cleanup 342
transport-nantes/tn_web pull request #370
Opened 2022-01-02 16:28 UTC by JeffAbrahamson

Clean up the mailing list / petition code a bit.

Note that this is based on a branch of yours, which looks ok to me but for which you didn't send a PR.  So perhaps there is something missing there.

2022-01-03 10:53 UTC, Shriukan33 requested changes

2022-01-03 10:58 UTC, JeffAbrahamson commented
Good catch, fixed.
Also removed the help text, which crispy provides.

2022-01-04 06:35 UTC, JeffAbrahamson commented
Should be good now.

2022-01-04 08:37 UTC, Shriukan33 approved these changes

2022-01-04 08:37 UTC, Shriukan33 commented
LGTM

2022-01-04 08:38 UTC, merged