Add tests topicblog form
transport-nantes/tn_web pull request #478
Opened 2022-02-14 16:17 UTC by mcmikashi

Implement functional test for topicblog form  with selenium

2022-02-14 16:51 UTC, Shriukan33 commented
As a general feeling, you should add some comments to structure the code and explain your intents, it would be easier to find your way inside it. 

It's a pretty long file, and there isn't a docstring and very sparse comments, it makes it harder to understand.

Will expand on the review later :)

2022-02-14 18:08 UTC, JeffAbrahamson commented
I don't know selenium well, but LGTM overall.

2022-02-15 12:37 UTC, Shriukan33 requested changes

2022-02-15 12:37 UTC, Shriukan33 commented on transport_nantes/topicblog/tests_topic_blog_form.py
> +        self.selenium.get('%s%s' % (self.live_server_url, '/tb/admin/t/new'))
Use a reverse() function, as the path is subject to changes, it's safer to use the name given to the url.

2022-02-15 12:38 UTC, Shriukan33 reviewed
Seems that Django CI finds errors in the test run

2022-02-15 13:37 UTC, Shriukan33 commented
LGTM

2022-02-15 13:39 UTC, merged