Add TopicBlogLauncher edit and add
transport-nantes/tn_web pull request #542
Opened 2022-03-09 17:29 UTC by mcmikashi

I implement the form I reoder the fields but don't know if this good or maybe split like topicblog item ?

And for need some detail for the template config for this object.

2022-03-09 20:01 UTC, JeffAbrahamson commented
Can template_name be a dropdown of available templates like for TBItem?

2022-03-09 20:02 UTC, JeffAbrahamson commented
Looks very good overall!

2022-03-10 14:35 UTC, mcmikashi commented
- I reorder the fields
- I add template config on TB launcher model
- The template name  field is now a select field

2022-03-10 15:13 UTC, Shriukan33 requested changes
Attempting to edit and save an existing item will raise an Error : 
![image](https://user-images.githubusercontent.com/70256364/157691335-a4cfd6c3-66c3-44c4-a0fa-af2af16293ce.png)

The ImageField being mandatory, it's not transferred between items. We already had this problem and solved it here : 
https://github.com/transport-nantes/tn_web/blob/bf005527ab8ad95ec6524cf02fc189e4b5286a61/transport_nantes/topicblog/views.py#L289

2022-03-10 17:44 UTC, JeffAbrahamson commented
In bf005527, please be careful of non-empty blank lines.  Your editor should have support to flag them to you.  Certainly `git diff` does.

![image](https://user-images.githubusercontent.com/1220683/157723480-7e562be5-f8ba-48f2-a1bf-5cd8eae962ab.png)

2022-03-10 17:47 UTC, JeffAbrahamson commented
When you copied and pasted the comments about content type, did you think about what they mean?  I'm pretty sure this comment in TBItem is obsolete and has no meaning, although the code that follows does have meaning.

So what concerns me is not that you copied and pasted: these classes are pretty parallel, and so that makes sense to get yourself started.  What concerns me is that you may have copied and pasted without reading and understanding.

The code that follows the comment looks correct.

2022-03-10 17:48 UTC, JeffAbrahamson commented on transport_nantes/topicblog/models.py
> +        "one_of_fields_for_publication": [['launcher_image',
Yes, I agree, either you provide an image and alt, or you provide neither, but not just one.

2022-03-11 16:44 UTC, mcmikashi commented
Before reviewing this PR, I need this PR to be reviewed  [PR 538](https://github.com/transport-nantes/tn_web/pull/538)

- I move the function get_image_fields from TopicBlogItem to TopicBlogOjectBase
- I add template_config in TopicBlogLauncher
- I add form_post_process in TopicBlogLauncherEdit
- I add edit test for topicblog launcher

The test fails because when I test topicblog:edit_launcher_by_slug
with a bad slug, I got a 200 code status.
What should happen when we get a bad slug on this page?

- Redirect to add ?
- Let the user edit ? (have to rewrite the slug)
- Let the user edit but the slug field is prefilled?

and what should happen if the user gives a good slug?

- let him edit the last published item?
- or let him edit the last added?

2022-03-14 07:55 UTC, JeffAbrahamson commented
Please mark PRs as drafts if tests are failing or they aren't otherwise ready for review.  The reviewers job is not to re-test your code but rather to make sure you're more or less going about your job correctly.  That is, they're offering a second set of eyes, but they aren't checking that you know how to do your job at all!

2022-03-16 19:35 UTC, mcmikashi commented
I have a little problem with edit with topicblog:edit_launcher_by_slug when we got the edit permission it’s always return a 200 status code even if we give a bad slug and with a good slug 
the fields stay empty.
Maybe we can relate this to the issue #552 or create a new one ?

2022-03-17 10:29 UTC, JeffAbrahamson commented
@mcmikashi You've unmarked this from being a draft, but you are indicating in your last comment that it's not ready?

2022-03-17 10:35 UTC, JeffAbrahamson commented
LGTM overall.
Tests pass, so I'm merging this.

2022-03-17 10:35 UTC, closed without merging