Improve validation of PressMention object on saving
transport-nantes/tn_web pull request #651
Opened 2022-04-07 14:40 UTC by mcmikashi

If the url cannot be request or don’t contain open graph image, it will return an error

2022-04-07 15:27 UTC, Shriukan33 requested changes
So this will check if the provided link does have Opengraph data at the moment you try to save the Pressmention, correct ?

2022-04-07 15:27 UTC, Shriukan33 commented on transport_nantes/press/views.py
> +                logger.error(f"Exeption when saving Pressmention {e}.")
Exception while saving Pressmention :

2022-04-07 15:27 UTC, Shriukan33 commented on transport_nantes/press/views.py
> +                ['Le site ne contient pas de donné Open Graph.']
données

2022-04-07 15:27 UTC, Shriukan33 commented on transport_nantes/press/views.py
>              logger.error(f"The url of the open graph image is not good.")
"is not good" ?

2022-04-07 19:02 UTC, mcmikashi commented
- Fix the spelling 
- Add comments

2022-04-08 06:38 UTC, JeffAbrahamson commented
LGTM.

2022-04-08 06:38 UTC, merged