Make beacon_view update the proper send records
transport-nantes/tn_web pull request #803
Opened 2022-06-15 13:08 UTC by Shriukan33

It previously always assumed we were using the TopicBlogEmail send
record.

Using a new token that encodes the send_record_class, we can fetch
the proper send record.

Closes  #799

2022-06-15 13:16 UTC, JeffAbrahamson commented on transport_nantes/topicblog/templates/topicblog/content_email_client.html
> +    <img src="{% absolute_url 'topicblog:beacon_view' beacon_token %}.gif" alt="space" height="1" width="1">
Yeah, this is definitely better self-documenting variable naming.  Good!

2022-06-15 14:39 UTC, Shriukan33 commented on transport_nantes/topicblog/views.py
> +    send_record_class_string, send_record_id = token_valid(token)
true, noted !

2022-06-15 15:08 UTC, Shriukan33 commented on transport_nantes/topicblog/views.py
> +    if send_record_class_string and send_record_id:
I don't think checking existence is that expensive ? Maybe the world isn't going to be the way I think it is and it's not all butterflies and magical ponies ... :laughing:

2022-06-15 15:19 UTC, Shriukan33 commented on transport_nantes/topicblog/views.py
> +        send_record = send_record_class.objects.get(pk=send_record_id)
Fixed with a try/except/else bloc

2022-06-16 10:06 UTC, JeffAbrahamson commented on transport_nantes/topicblog/views.py
> +    if send_record_class_string and send_record_id:
Agreed, although then you might just do an extra check.

The thing is that if you check both without comment, a reader might think "hmm, there's some undocumented subtlety that could lead the interface spec not to be satisfied".

So then you'd say something like
```
    if send_record_id:
        # token_valid() is guaranteed to set both send_record_id and email.
        CHECK(email is None)
        ...
```
where `CHECK` is something that 500's if email is None.

2022-06-16 10:25 UTC, Shriukan33 commented on transport_nantes/topicblog/views.py
> +    if send_record_class_string and send_record_id:
Did add a check and logs

2022-06-16 14:48 UTC, JeffAbrahamson requested changes
Probably correct, but some style suggestions...

2022-06-16 14:48 UTC, JeffAbrahamson commented on transport_nantes/topicblog/views.py
> +            logger.info(
You are catching the valueError you just threw?  Why don't you simply handle it where you threw it and exit right away?  It saves state for the reader.

2022-06-16 14:48 UTC, JeffAbrahamson commented on transport_nantes/topicblog/views.py
> +        else:
What is this an `else` to?  It's indented too far to go with `if send_record_class_string`, but it's a bit weird to say `try...else`.  Also it's a bit weird to say `else if` on two lines.

Can you clean up and handle all the cases above?  What should `beacon_view()` do on those exceptions?  It currently returns a response no matter what, which I think is correct (serve the pixel, even if we learned nothing), but you should comment that it's what you mean.

2022-06-16 17:53 UTC, Shriukan33 commented
Simplified the beacon_view's flow.

2022-06-16 19:56 UTC, JeffAbrahamson commented
LGTM.

2022-06-16 19:58 UTC, JeffAbrahamson approved these changes
LGTM.

2022-06-16 20:36 UTC, merged