Remove references to "servable"
transport-nantes/tn_web pull request #815
Opened 2022-06-21 13:04 UTC by Shriukan33

We don't use this attribute anymore. Its presence in templates showed
buttons that had no functionality.

Closes #462

2022-06-21 14:52 UTC, JeffAbrahamson requested changes
Is this function still correct?
```
    def get_servable_status(self):
        """Return True if page is user visible, False otherwise."""
        if self.publication_date is None or \
                datetime.now(timezone.utc) < self.publication_date:
            return False
        return True
```

2022-06-21 14:56 UTC, Shriukan33 commented
> Is this function still correct?
> 
> ```
>     def get_servable_status(self):
>         """Return True if page is user visible, False otherwise."""
>         if self.publication_date is None or \
>                 datetime.now(timezone.utc) < self.publication_date:
>             return False
>         return True
> ```

Yes it is :)
We use that to check that the item we're selecting is indeed servable (has a publication date that is inferior to now)
It comes after we filter and order. It's a very edge case, as we don't usually set a publication date to future (can only be done in admin).

2022-06-21 15:03 UTC, JeffAbrahamson commented
> > Is this function still correct?
> > ```
> >     def get_servable_status(self):
> >         """Return True if page is user visible, False otherwise."""
> >         if self.publication_date is None or \
> >                 datetime.now(timezone.utc) < self.publication_date:
> >             return False
> >         return True
> > ```
> 
> Yes it is :) We use that to check that the item we're selecting is indeed servable (has a publication date that is inferior to now) It comes after we filter and order. It's a very edge case, as we don't usually set a publication date to future (can only be done in admin).

Maybe just deserves a comment to indicate that extra dependency, that this isn't enough to determine servability, that there are other constraints?

2022-06-22 08:19 UTC, Shriukan33 commented
Added a comment in the docstring

2022-06-23 14:59 UTC, JeffAbrahamson approved these changes
LGTM.

2022-06-23 16:15 UTC, merged