Switch main dashbaord to a table
transport-nantes/tn_web pull request #908
Opened 2022-08-25 09:06 UTC by Shriukan33

This table regroups everything the former dashboard was doing, but in a
more compact way.
It is responsive.

It doesn't handle permissions checks before displaying, this is coming a bit later so it's a lighter PR to digest. 

Part of #831

2022-08-25 12:58 UTC, JeffAbrahamson commented
The code looks good.

Can you think of many dashboard that have a big title "dashboard" at the top?  Usually things try to present themselves well enough that you don't have to say "this is a loaf of bread".

I think the internal names for things, based on our usage, is stuff like `TBItem` etc.  But that's not terribly useful to outsiders, so maybe we could use simple French words: `blog`, `mail`, `CP`, `carré`, `inscription`.  What would you call these things when talking to a non-dev?

It's a strange abstraction to a non-developer to think that an email is also a blog post and that a blog post is or isn't an email.  Think how a volunteer or non technical staffer would view these things.  On that subject, you've organised it the way our code is organised, but few non-dev's would find that logical, I expect.

```
blog     Articles de blog
mail     Marketing mails qui peuvent également être visionné sur web
CP       Communiqués de presse
carré    Un carré qui peut être présenté dans le rubrique de nos projets
inscription   Pages qui incite le visiteur de s'inscrire une liste de diffusion (y compris pétition)
presse   Mentions des Mobilitains dans la presse
diffusion   Listes de diffusion, de newsletters et pétitions
```

Why is the list view icon for mailinglists different from the list view icon for everything else?  Indeed, I'd say it should have a "+" icon, too, just inactive (because we haven't implemented that yet).

2022-08-25 13:01 UTC, JeffAbrahamson requested changes
See long-ish comment in the conversation pain.  It's just about presentation, the code otherwise looks good.

2022-08-29 08:21 UTC, Shriukan33 commented
Applied your suggestions : 
![image](https://user-images.githubusercontent.com/70256364/187157186-d558f917-9f6d-46eb-9dcf-12e5b1d1ed9d.png)

2022-08-30 07:22 UTC, JeffAbrahamson approved these changes
LGTM.

2022-08-30 07:32 UTC, merged